project:
  type: website

website:
  title: "quarto-lock"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: customize.qmd
        text: Customize UI
      - href: second.qmd
        text: Second page
      - href: https://github.com/lsbjordao/quarto-lock
        text: GitHub

format:
  html:
    theme: cosmo

filters:
  - quarto-lock
