project:
  type: website

website:
  title: "quarto-lock"
  site-url: "https://lsbjordao.github.io/quarto-lock/"
  google-analytics: "G-Z2B44PKNCV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publishing.qmd
        text: Publishing
      - href: customize.qmd
        text: Customize UI
      - href: https://lsbjordao.github.io/quarto-lock-demo/
        text: Live Demo
      - href: https://github.com/lsbjordao/quarto-lock
        text: GitHub

format:
  html:
    theme: cosmo
